nfl_teams<-c(
  "Atlanta Falcons" = "ATL",
  "Philadelphia Eagles" = "PHI",
  "Baltimore Ravens" = "BAL",
  "Buffalo Bills" = "BUF",
  "Jacksonville Jaguars" = "JAX",
  "New York Giants" = "NYG",
  "New Orleans Saints" = "NO",
  "Tampa Bay Buccaneers" = "TB",
  "New England Patriots" = "NE",
  "Houston Texans" = "HOU",
  "Minnesota Vikings" = "MIN",
  "San Francisco 49ers" = "SF",
  "Tennessee Titans" = "TEN",
  "Miami Dolphins" = "MIA",
  "Cincinnati Bengals" = "CIN",
  "Indianapolis Colts" = "IND",
  "Pittsburgh Steelers" = "PIT",
  "Cleveland Browns" = "CLE",
  "Los Angeles Chargers" = "LAC",
  "Kansas City Chiefs" = "KC",
  "Denver Broncos" = "DEN",
  "Seattle Seahawks" = "SEA",
  "Dallas Cowboys" = "DAL",
  "Carolina Panthers" = "CAR",
  "Washington Commanders" = "WAS",
  "Arizona Cardinals" = "ARI",
  "Green Bay Packers" = "GB",
  "Chicago Bears" = "CHI",
  "New York Jets" = "NYJ",
  "Detroit Lions" = "DET",
  "Oakland Raiders" = "OAK",
  "Los Angeles Rams" = "LA"
)

num_vars<-c(
  "Offense's Win Probability Before Play" = "wp",
  "Win Probability Added on Play" = "wpa",
  "Score Differential Before Play (Offense-Defense)" = "score_differential",
  "Yards Gained on Play" = "yards_gained"
)

all_vars<-c(
  "Game ID Number" = "game_id",
  "Game Date" = "game_date",
  "Home Team" = "home_team",
  "Away Team" = "away_team",
  "Team with Position/on Offense" = "posteam",
  "Quarter" = "qtr",
  "Game Clock" = "time",
  "Down" = "down",
  "Yards to Go" = "ydstogo",
  "Yardline" = "yrdln",
  "Home Team Score" = "total_home_score",
  "Away Team Score" = "total_away_score",
  "Score Differential" = "score_differential",
  "Play Description" = "desc",
  "Play Type" = "play_type",
  "Yards Gained on Play" = "yards_gained",
  "Win Probability Before the Play" = "wp",
  "Win Probability Added on the Play" = "wpa",
  "Fumble Lost on Play?" = "fumble_lost",
  "Interception on Play?" = "interception"
)
